### ISSUE TITLE
Investigate advanced search-style boolean ORs

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sw_index_tests#191]
```
  5) advanced search author + title author Stalin title 'rechi OR sochineniia' title rechi OR sochineniia
     Failure/Error: expect(resp.size).to be >= 2200

       expected: >= 2200
            got:    2
     # ./spec/advanced_search_spec.rb:205:in `block (4 levels) in <top (required)>'

  6) advanced search author + title author Stalin title 'rechi OR sochineniia' author and title both terms optional
     Failure/Error: expect(resp.size).to be >= 20

       expected: >= 20
            got:    0
     # ./spec/advanced_search_spec.rb:223:in `block (4 levels) in <top (required)>'
```

**Comment by mejackreed** [comment]
In looking at these searches in the application code, 

```
  6) advanced search author + title author Stalin title 'rechi OR sochineniia' author and title both terms optional
```

returns the exact same responses (for current Solr 4 and Solr 6.6.1)

and 
```
  5) advanced search author + title author Stalin title 'rechi OR sochineniia' title rechi OR sochineniia
```
returns one difference

**Comment by cbeer** [comment]
👍 I wonder if we can capture the new solr query and plan to use it in the test suite instead?

**Comment by mejackreed** [comment]
Yep.. I'm already on it. Looking to abstract "helper" methods that will create the advanced search query in our test suite.

**Comment by mejackreed** [comment]
SearchWorks codebase is using complex logic to determine whether to use dismax or edismax for a certain query. The tests here do not reflect what exactly SearchWorks queries are being passed to Solr.
