### ISSUE TITLE
Investigate CJK title search that now returns 0 results 

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sw_index_tests#195]
```
  128) Chinese Title People's Republic of China spaces behaves like both scripts get expected result size title search has between 850 and 1100 results
       Failure/Error: expect(resp.size).to be >= min

         expected: >= 850
              got:    0
       Shared Example Group: "expected result size" called from ./spec/support/shared_examples_cjk.rb:23
       Shared Example Group: "both scripts get expected result size" called from ./spec/cjk/chinese_title_spec.rb:126
       # ./spec/support/shared_examples_cjk.rb:7:in `block (2 levels) in <top (required)>'

  129) Chinese Title People's Republic of China spaces behaves like both scripts get expected result size title search has between 850 and 1100 results
       Failure/Error: expect(resp.size).to be >= min

         expected: >= 850
              got:    0
       Shared Example Group: "expected result size" called from ./spec/support/shared_examples_cjk.rb:24
       Shared Example Group: "both scripts get expected result size" called from ./spec/cjk/chinese_title_spec.rb:126
       # ./spec/support/shared_examples_cjk.rb:7:in `block (2 levels) in <top (required)>'
```

**Comment by mejackreed** [comment]
Spaces?

**Comment by cbeer** [comment]
Yes; and I've confirmed with Vitus that the way the string is written with spaces is non-sensical, so we should be able to remove this test.
