### ISSUE TITLE
Investigate known item search with punctuation

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sw_index_tests#198]
```
  382) hyphen in queries 'Silence : a thirteenth-century French romance' behaves like hyphens without spaces imply phrase title phrase search for entire query should ignore hyphen
       Failure/Error: expect(@tresp_whole_phrase).to have_the_same_number_of_documents_as(@tresp_whole_phrase_no_hyphen)

         expected 0 documents in Solr response {'responseHeader' => {"zkConnected"=>true, "status"=>0, "QTime"=>18, "params"=>{"q"=>"{!qf=$qf_title pf=$pf_title pf3=$pf3_title pf2=$pf2_title}\"Silence : a thirteenth century French romance\"", "qt"=>"search", "fl"=>"id", "testing"=>"sw_index_test", "facet"=>"false", "wt"=>"json"}}, 'response' => {'numFound' => 2, ...} ... }
         Diff:


         @@ -1,15 +1,14 @@
          {"responseHeader"=>
            {"zkConnected"=>true,
             "status"=>0,
         -   "QTime"=>18,
         +   "QTime"=>22,
             "params"=>
              {"q"=>
         -      "{!qf=$qf_title pf=$pf_title pf3=$pf3_title pf2=$pf2_title}\"Silence : a thirteenth century French romance\"",
         +      "{!qf=$qf_title pf=$pf_title pf3=$pf3_title pf2=$pf2_title}\"Silence : a thirteenth-century French romance\"",
               "qt"=>"search",
               "fl"=>"id",
               "testing"=>"sw_index_test",
               "facet"=>"false",
               "wt"=>"json"}},
         - "response"=>
         -  {"numFound"=>2, "start"=>0, "docs"=>[{"id"=>"12626562"}, {"id"=>"2416395"}]}}
         + "response"=>{"numFound"=>0, "start"=>0, "docs"=>[]}}
       Shared Example Group: "hyphens without spaces imply phrase" called from ./spec/punctuation/hyphen_spec.rb:298
       # ./spec/punctuation/hyphen_spec.rb:51:in `block (3 levels) in <top (required)>'

  383) hyphen in queries 'Color-blindness [print/digital]; its dangers and its detection' should have great results for query
       Failure/Error: expect(@resp_whole_phrase).to include("10858119").in_first(first_x).documents

         expected response to include document "10858119" in first 2 results: {"responseHeader"=>{"zkConnected"=>true, "status"=>0, "QTime"=>96, "params"=>{"q"=>"\"Color-blindness [print/digital]; its dangers and its detection\"", "fl"=>"id", "testing"=>"sw_index_test", "facet"=>"false", "wt"=>"json"}}, "response"=>{"numFound"=>0, "start"=>0, "docs"=>[]}}
         Diff:
         @@ -1,2 +1,12 @@
         -["10858119"]
         +{"responseHeader"=>
         +  {"zkConnected"=>true,
         +   "status"=>0,
         +   "QTime"=>96,
         +   "params"=>
         +    {"q"=>"\"Color-blindness [print/digital]; its dangers and its detection\"",
         +     "fl"=>"id",
         +     "testing"=>"sw_index_test",
         +     "facet"=>"false",
         +     "wt"=>"json"}},
         + "response"=>{"numFound"=>0, "start"=>0, "docs"=>[]}}
       # ./spec/punctuation/hyphen_spec.rb:351:in `block (3 levels) in <top (required)>'

```

**Comment by cbeer** [comment]
Maybe of interest: https://github.com/pulibrary/pul_solr/pull/12?

**Comment by cbeer** [comment]
Fixed by https://github.com/sul-dlss/sul-solr-configs/pull/145?
