### ISSUE TITLE
Investigate Kanji searches returning dramatically fewer results

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sw_index_tests#202]
```
  221) Japanese Kanji variants modern Kanji != simplified Han weekly behaves like both scripts get expected result size title search has between 80 and 110 results
       Failure/Error: expect(resp.size).to be >= min

         expected: >= 80
              got:    5
       Shared Example Group: "expected result size" called from ./spec/support/shared_examples_cjk.rb:23
       Shared Example Group: "both scripts get expected result size" called from ./spec/cjk/japanese_han_variants_spec.rb:145
       # ./spec/support/shared_examples_cjk.rb:7:in `block (2 levels) in <top (required)>'

  222) Japanese Kanji variants modern Kanji != simplified Han weekly behaves like both scripts get expected result size title search has between 80 and 110 results
       Failure/Error: expect(resp.size).to be >= min

         expected: >= 80
              got:    5
       Shared Example Group: "expected result size" called from ./spec/support/shared_examples_cjk.rb:24
       Shared Example Group: "both scripts get expected result size" called from ./spec/cjk/japanese_han_variants_spec.rb:145
       # ./spec/support/shared_examples_cjk.rb:7:in `block (2 levels) in <top (required)>'
```

**Comment by cbeer** [comment]
They are being treated as equivalent. The difference seems to be many of the current results get parsed as quadgrams (as part of names of publications?) and the search term parsed as a bigram.

**Comment by cbeer** [comment]
"Weekly" should probably be treated a different term and bi-grammed in the title.
