### ISSUE TITLE
Investigate Japanese series search that returns no results

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sw_index_tests#203]
```

  223) Japanese Series humorous behaves like good results for query series search has between 1 and 3 results
       Failure/Error: expect(resp.size).to be >= min

         expected: >= 1
              got:    0
       Shared Example Group: "expected result size" called from ./spec/support/shared_examples_cjk.rb:35
       Shared Example Group: "good results for query" called from ./spec/cjk/japanese_series_spec.rb:7
       # ./spec/support/shared_examples_cjk.rb:7:in `block (2 levels) in <top (required)>'


  224) Japanese Series humorous behaves like good results for query finds "6329172" in first 1 results
       Failure/Error: expect(resp).to include(id_list).in_first(num).results

         expected response to include document "6329172" in first 1 results: {"responseHeader"=>{"zkConnected"=>true, "status"=>0, "QTime"=>2, "params"=>{"mm"=>"3<86%", "q"=>"{!qf=$qf_series_cjk pf=$pf_series_cjk pf3=$pf3_series_cjk pf2=$pf2_series_cjk}ユニークな", "qs"=>"0", "fl"=>"id", "testing"=>"sw_index_test", "facet"=>"false", "wt"=>"json"}}, "response"=>{"numFound"=>0, "start"=>0, "docs"=>[]}}
         Diff:
         @@ -1,2 +1,15 @@
         -["6329172"]
         +{"responseHeader"=>
         +  {"zkConnected"=>true,
         +   "status"=>0,
         +   "QTime"=>2,
         +   "params"=>
         +    {"mm"=>"3<86%",
         +     "q"=>
         +      "{!qf=$qf_series_cjk pf=$pf_series_cjk pf3=$pf3_series_cjk pf2=$pf2_series_cjk}ユニークな",
         +     "qs"=>"0",
         +     "fl"=>"id",
         +     "testing"=>"sw_index_test",
         +     "facet"=>"false",
         +     "wt"=>"json"}},
         + "response"=>{"numFound"=>0, "start"=>0, "docs"=>[]}}
       Shared Example Group: "best matches first" called from ./spec/support/shared_examples_cjk.rb:36
       Shared Example Group: "good results for query" called from ./spec/cjk/japanese_series_spec.rb:7
       # ./spec/support/shared_examples_cjk.rb:30:in `block (2 levels) in <top (required)>'
```

**Comment by cbeer** [comment]
The katakana used in the query vs expected item is pretty different and may have relied on mm fudging to get the right result.

I'm a little confused how the original ticket led to this particular test, so it may be worth following up on.

**Comment by cbeer** [comment]
There's something about the last character that we should possibly be handling with Japanese stemming?
