### ISSUE TITLE
Investigate Japanese title search with dramatically more results

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sw_index_tests#205]
```

  229) Japanese Title searches editorial behaves like both scripts get expected result size title search has between 50 and 100 results
       Failure/Error: expect(resp.size).to be <= max

         expected: <= 100
              got:    228
       Shared Example Group: "expected result size" called from ./spec/support/shared_examples_cjk.rb:23
       Shared Example Group: "both scripts get expected result size" called from ./spec/cjk/japanese_title_spec.rb:28
       # ./spec/support/shared_examples_cjk.rb:8:in `block (2 levels) in <top (required)>'

  230) Japanese Title searches editorial behaves like both scripts get expected result size title search has between 50 and 100 results
       Failure/Error: expect(resp.size).to be <= max

         expected: <= 100
              got:    228
       Shared Example Group: "expected result size" called from ./spec/support/shared_examples_cjk.rb:24
       Shared Example Group: "both scripts get expected result size" called from ./spec/cjk/japanese_title_spec.rb:28
       # ./spec/support/shared_examples_cjk.rb:8:in `block (2 levels) in <top (required)>'
```

**Comment by cbeer** [comment]
We're now parsing the query as 2 unigrams, so getting more hits probably makes sense.
