### ISSUE TITLE
Investigate Japanese title search that returns fewer results

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sw_index_tests#206]
```

  241) Japanese Title searches Study of Buddhism behaves like both scripts get expected result size title search has between 200 and 300 results
       Failure/Error: expect(resp.size).to be >= min

         expected: >= 200
              got:    45
       Shared Example Group: "expected result size" called from ./spec/support/shared_examples_cjk.rb:23
       Shared Example Group: "both scripts get expected result size" called from ./spec/cjk/japanese_title_spec.rb:120
       # ./spec/support/shared_examples_cjk.rb:7:in `block (2 levels) in <top (required)>'

  242) Japanese Title searches Study of Buddhism behaves like both scripts get expected result size title search has between 200 and 300 results
       Failure/Error: expect(resp.size).to be >= min

         expected: >= 200
              got:    45
       Shared Example Group: "expected result size" called from ./spec/support/shared_examples_cjk.rb:24
       Shared Example Group: "both scripts get expected result size" called from ./spec/cjk/japanese_title_spec.rb:120
       # ./spec/support/shared_examples_cjk.rb:7:in `block (2 levels) in <top (required)>'
```

**Comment by cbeer** [comment]
N-gramming difference; this was also one of the super-user queries that was blocked because we were missing our custom variants mapping.

**Comment by cbeer** [comment]
This should be ok; many of the missing results are other "compound" words that include the study-term, but are actually other things.
